-- Generated by scripts/generate-seed.ts from the Google Sheet
-- "Master_Database_Komersial_Compiled". Do not edit by hand; run `pnpm seed:generate`.
--
-- Dates are the Sheet's own and are maintained there. They are no longer re-anchored
-- on seeding: the workbook needed that because its dates aged, the Sheet does not.
--
-- A contract with a null `cabang` is the Sheet's "All Station" — work belonging to
-- every airport, and therefore visible at every branch rather than at none.

begin;

-- ─── Replace what the Sheet owns ──────────────────────────────────────────
-- Deleting a contract cascades to its scenarios and notifications, which is what
-- makes re-seeding a clean replacement rather than a merge.

delete from public.cases;
delete from public.contracts;
delete from public.customers;
delete from auth.users where email in ('vp@gapura.test', 'commercial@gapura.test', 'cabang.cgk@gapura.test');

-- ─── Demo accounts ────────────────────────────────────────────────────────
-- One login per role. VP and Commercial are unscoped; the GM Cabang is confined to
-- one station and is the boundary a judge can sign in and see.

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  -- GoTrue scans these into non-nullable Go strings; leaving them NULL makes
  -- every sign-in fail with "Database error querying schema".
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) values (
  '00000000-0000-0000-0000-000000000000', 'ffab5dd0-1bfa-42aa-bec3-ca9f69035e81', 'authenticated', 'authenticated',
  'vp@gapura.test', crypt('Gapura2026!', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{"nama":"VP"}',
  now(), now(), '', '', '', '', '', '', '', ''
);

insert into auth.identities (
  id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at
) values (
  gen_random_uuid(), 'ffab5dd0-1bfa-42aa-bec3-ca9f69035e81', 'ffab5dd0-1bfa-42aa-bec3-ca9f69035e81', 'email',
  '{"sub":"ffab5dd0-1bfa-42aa-bec3-ca9f69035e81","email":"vp@gapura.test","email_verified":true}',
  now(), now(), now()
);

insert into public.profiles (id, nama, role, business_line, cabang) values (
  'ffab5dd0-1bfa-42aa-bec3-ca9f69035e81', 'VP', 'vp',
  null,
  null
);

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  -- GoTrue scans these into non-nullable Go strings; leaving them NULL makes
  -- every sign-in fail with "Database error querying schema".
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) values (
  '00000000-0000-0000-0000-000000000000', '12e61f59-7f77-4100-a489-abbaf9584029', 'authenticated', 'authenticated',
  'commercial@gapura.test', crypt('Gapura2026!', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{"nama":"Commercial"}',
  now(), now(), '', '', '', '', '', '', '', ''
);

insert into auth.identities (
  id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at
) values (
  gen_random_uuid(), '12e61f59-7f77-4100-a489-abbaf9584029', '12e61f59-7f77-4100-a489-abbaf9584029', 'email',
  '{"sub":"12e61f59-7f77-4100-a489-abbaf9584029","email":"commercial@gapura.test","email_verified":true}',
  now(), now(), now()
);

insert into public.profiles (id, nama, role, business_line, cabang) values (
  '12e61f59-7f77-4100-a489-abbaf9584029', 'Commercial', 'commercial',
  null,
  null
);

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  -- GoTrue scans these into non-nullable Go strings; leaving them NULL makes
  -- every sign-in fail with "Database error querying schema".
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) values (
  '00000000-0000-0000-0000-000000000000', '6cd395ca-0d4e-4169-a3ad-186e06d1ff19', 'authenticated', 'authenticated',
  'cabang.cgk@gapura.test', crypt('Gapura2026!', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{"nama":"GM Cabang CGK"}',
  now(), now(), '', '', '', '', '', '', '', ''
);

insert into auth.identities (
  id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at
) values (
  gen_random_uuid(), '6cd395ca-0d4e-4169-a3ad-186e06d1ff19', '6cd395ca-0d4e-4169-a3ad-186e06d1ff19', 'email',
  '{"sub":"6cd395ca-0d4e-4169-a3ad-186e06d1ff19","email":"cabang.cgk@gapura.test","email_verified":true}',
  now(), now(), now()
);

insert into public.profiles (id, nama, role, business_line, cabang) values (
  '6cd395ca-0d4e-4169-a3ad-186e06d1ff19', 'GM Cabang CGK', 'cabang',
  null,
  'CGK'
);

-- ─── Customers (CRM_Data) ─────────────────────────────────────────────────

insert into public.customers (customer_id, nama, rfm_status, frequency_score, monetary_score, recency_score) values
  ('CUST-001', 'Garuda Indonesia', 'MEDIUM', 2, 3, 3),
  ('CUST-002', 'Citilink', 'LOW', 1, 1, 1),
  ('CUST-003', 'Pelita Air', 'HIGH', 3, 3, 3),
  ('CUST-004', 'Asia Flight Service', 'HIGH', 3, 3, 3),
  ('CUST-005', 'Batik Air', 'LOW', 1, 1, 1),
  ('CUST-008', 'Airnesia', 'HIGH', 3, 3, 3),
  ('CUST-009', 'Super Air Jet', 'LOW', 1, 1, 1),
  ('CUST-006', 'DPR RI', 'HIGH', 3, 3, 3),
  ('CUST-007', 'Jogja Flight', 'MEDIUM', 3, 3, 2);

-- ─── Contracts (Compiled_Contracts), one row per station ──────────────────
-- The Sheet writes multi-station work either as one row listing several stations or
-- as several rows priced individually; both arrive here as one row per station.
--
-- `min_gpm_target` and `service_type` are null throughout: the Sheet has no column
-- for either, and Revenue_Data still keys on the retired CUST-GH-* ids so it cannot
-- supply the target. Nulls rather than invented figures.

insert into public.contracts (
  id, contract_no, customer_id, cabang, business_line, contract_start_date, contract_end_date,
  tarif, cost, pic_nama, pic_telepon, pic_email, remarks, latest_contract
) values
  ('fecfc127-9130-4b27-b6e9-6cf3e1e4988a', 'K-001', 'CUST-001', null, 'Ground Handling',
   '2025-09-15', '2026-09-15', 22000000, 17000000,
   'Baron', '6281124124', 'Baron@gapura.id', 'Airlines', 'SGHA ANNEX B.1.0XXX'),
  ('56ce198e-f66b-42a8-aad6-ee5afccc41a1', 'K-002', 'CUST-002', null, 'Ground Handling',
   '2025-08-30', '2026-08-30', 18500000, 14800000,
   'Chaerul', '6281124124124', 'Chaerul@gapura.id', 'Airlines', 'PKS'),
  ('64bbaa7f-4647-4e07-b297-3e04aa3c86cd', 'K-003', 'CUST-003', null, 'Ground Handling',
   '2025-10-12', '2026-10-12', 16000000, 12400000,
   'Luigi', '62811241212556', 'Luigi@gapura.id', 'Airlines', 'AD.1.4'),
  ('6f845967-6667-4d3d-b64e-75ad670d7e83', 'K-004', 'CUST-004', 'MDC', 'Ground Handling',
   '2025-07-25', '2026-07-25', 9800000, 8100000,
   'Panji', '62812634654743', 'Panji@gapura.id', 'FBO', 'PKS'),
  ('8bc77357-4879-4395-942d-783094f3e7a8', 'K-004', 'CUST-004', 'BTH', 'Ground Handling',
   '2025-07-25', '2026-07-25', 9800000, 8100000,
   'Panji', '62812634654743', 'Panji@gapura.id', 'FBO', 'PKS'),
  ('10415bf5-2b0f-480f-9806-a344f27c0112', 'K-005', 'CUST-005', null, 'Ground Handling',
   '2025-11-05', '2026-11-05', 10500000, 8200000,
   'Gumilang', '6281124999989', 'Gumilang@gapura.id', 'GSE', 'SGHA ANNEX B.2.0XXX'),
  ('23734f06-7f02-42fe-8aad-d520059d5051', 'K-006', 'CUST-005', 'UPG', 'Ground Handling',
   '2025-08-15', '2026-08-15', 13800000, 11500000,
   'Adakil', '628123534367', 'Adakil@gapura.id', 'Airlines', 'AD.1.5'),
  ('2a225798-c494-43ca-b184-790d54b00551', 'K-006', 'CUST-005', 'SUB', 'Ground Handling',
   '2025-08-15', '2026-08-15', 13800000, 11500000,
   'Adakil', '628123534367', 'Adakil@gapura.id', 'Airlines', 'AD.1.5'),
  ('7a192d4c-17d7-44c2-b583-f2dca248e998', 'K-010', 'CUST-008', 'CGK', 'Ground Handling',
   '2025-09-01', '2026-09-01', 14000000, 11200000,
   'Lusi', null, null, 'Airlines', 'PKS-ARN-2026'),
  ('ff026e4e-d091-4b27-8e78-e32ce3a44060', 'K-010', 'CUST-008', 'DPS', 'Ground Handling',
   '2025-09-01', '2026-09-01', 12500000, 10000000,
   'Jalal', null, null, 'Airlines', 'PKS-ARN-2026'),
  ('5f98ed02-4d0c-4b91-9d81-319878d71a20', 'K-011', 'CUST-009', null, 'Ground Handling',
   '2025-10-01', '2026-10-01', 13000000, 10400000,
   'Ludin', null, null, 'Airlines', 'PKS-SAJ-2026'),
  ('7935129c-ddc1-4d47-8e35-feb02fb48468', 'K-009', 'CUST-001', 'CGK', 'Cargo Handling',
   '2025-08-15', '2026-12-15', 11200000, 9000000,
   'Asep', null, null, 'Cargo', 'PKS'),
  ('abab7032-99d7-4ee9-ae55-8bcd62eeb71e', 'K-009', 'CUST-001', 'SUB', 'Cargo Handling',
   '2025-08-15', '2026-12-15', 11200000, 9000000,
   'Asep', null, null, 'Cargo', 'PKS'),
  ('1ed13706-1071-4daf-a3bd-dbf1166b568d', 'K-007', 'CUST-006', null, 'Ancillary Business',
   '2025-08-15', '2026-12-15', 7500000, 6000000,
   'Bangsa', '628123123245', 'Bangsa@gapura.id', 'Joumpa', 'AD.1.6'),
  ('3bb81b7d-5f3d-49d8-be80-e0f7bd388eeb', 'K-008', 'CUST-007', 'CGK', 'Ancillary Business',
   '2025-08-15', '2026-12-15', 5200000, 4000000,
   'Cecep', null, null, 'Learning Centre', 'AD.1.8');

-- ─── Service cases (CS_Data) ──────────────────────────────────────────────

insert into public.cases (customer_id, description, status) values
  ('CUST-001', 'Kerusakan peralatan GSE saat pushback pesawat wide-body.', 'OPEN'),
  ('CUST-002', 'Keterlambatan penanganan bagasi (delay 45 menit) GA-120.', 'CLOSED'),
  ('CUST-003', 'Tumpahan oli hidrolik pesawat di apron saat bongkar muat bagasi.', 'OPEN'),
  ('CUST-004', 'Keterlambatan bongkar muat kargo kargo utama (delay 60 menit).', 'CLOSED'),
  ('CUST-005', 'Komplain suhu ruang pendingin naik melebihi batas toleransi.', 'OPEN'),
  ('CUST-005', 'Kerusakan fisik pada kotak pengiriman buah segar kustomer.', 'OPEN'),
  ('CUST-008', 'Kehilangan satu koli dokumen ekspres (sudah ditemukan kembali).', 'CLOSED'),
  ('CUST-008', 'Fasilitas AC di executive lounge bandara sempat mati selama 2 jam.', 'CLOSED'),
  ('CUST-009', 'Kebocoran atap gerai ritel di area terminal internasional.', 'OPEN'),
  ('CUST-009', 'Antrean panjang valet parking saat jam sibuk penerbangan pagi.', 'OPEN');

commit;
