-- Generated by scripts/generate-seed.ts from Master_Database_Komersial_Compiled.xlsx.
-- Do not edit by hand; run `pnpm seed:generate` instead.
--
-- Contract end dates are re-anchored on every reset: current_date + (source_end_date - '2026-08-10'),
-- which reproduces the pipeline of Nonaktif 3 / Kritis 3 / Perlu Perhatian 5 / Aman 9.

begin;

-- ─── Demo accounts ────────────────────────────────────────────────────────
-- One Commercial user per business line plus one VP: four logins, four distinct
-- row sets. The largest Commercial scope still hides 60% of the portfolio.

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  -- GoTrue scans these into non-nullable Go strings; leaving them NULL makes
  -- every sign-in fail with "Database error querying schema".
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) values (
  '00000000-0000-0000-0000-000000000000', '9cb168d5-e200-44fa-b3fc-772fa925d86c', 'authenticated', 'authenticated',
  'vp@gapura.test', crypt('Gapura2026!', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{"nama":"VP"}',
  now(), now(), '', '', '', '', '', '', '', ''
);

insert into auth.identities (
  id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at
) values (
  gen_random_uuid(), '9cb168d5-e200-44fa-b3fc-772fa925d86c', '9cb168d5-e200-44fa-b3fc-772fa925d86c', 'email',
  '{"sub":"9cb168d5-e200-44fa-b3fc-772fa925d86c","email":"vp@gapura.test","email_verified":true}',
  now(), now(), now()
);

insert into public.profiles (id, nama, role, business_line) values (
  '9cb168d5-e200-44fa-b3fc-772fa925d86c', 'VP', 'vp',
  null
);

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  -- GoTrue scans these into non-nullable Go strings; leaving them NULL makes
  -- every sign-in fail with "Database error querying schema".
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) values (
  '00000000-0000-0000-0000-000000000000', '2cf9fb8c-b338-45dc-a715-a1bc84bebe9c', 'authenticated', 'authenticated',
  'commercial@gapura.test', crypt('Gapura2026!', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{"nama":"Commercial"}',
  now(), now(), '', '', '', '', '', '', '', ''
);

insert into auth.identities (
  id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at
) values (
  gen_random_uuid(), '2cf9fb8c-b338-45dc-a715-a1bc84bebe9c', '2cf9fb8c-b338-45dc-a715-a1bc84bebe9c', 'email',
  '{"sub":"2cf9fb8c-b338-45dc-a715-a1bc84bebe9c","email":"commercial@gapura.test","email_verified":true}',
  now(), now(), now()
);

insert into public.profiles (id, nama, role, business_line) values (
  '2cf9fb8c-b338-45dc-a715-a1bc84bebe9c', 'Commercial', 'commercial',
  null
);

-- ─── Customers (CRM_Data) ─────────────────────────────────────────────────

insert into public.customers (customer_id, nama, rfm_status) values
  ('CUST-GH-001', 'Garuda Nusantara Airlines', 'HIGH'),
  ('CUST-GH-002', 'Lion Star Airways', 'HIGH'),
  ('CUST-GH-003', 'Batavia Air Charter', 'MEDIUM'),
  ('CUST-GH-004', 'Celebes Inter Air', 'MEDIUM'),
  ('CUST-GH-005', 'Sumatra Express Airways', 'LOW'),
  ('CUST-GH-006', 'Borneo Cargo Wings', 'HIGH'),
  ('CUST-GH-007', 'Air Papua Charter', 'LOW'),
  ('CUST-GH-008', 'Bali Sunshine Airways', 'MEDIUM'),
  ('CUST-CG-009', 'Logistik Maju Bersama', 'HIGH'),
  ('CUST-CG-010', 'Jasa Kilat Express', 'MEDIUM'),
  ('CUST-CG-011', 'Samudera Cold Chain', 'HIGH'),
  ('CUST-CG-012', 'Agro Trans Nusantara', 'LOW'),
  ('CUST-CG-013', 'Indo Logistic Solusi', 'LOW'),
  ('CUST-CG-014', 'Global Express Courier', 'HIGH'),
  ('CUST-CG-015', 'Fast Cargo Indonesia', 'MEDIUM'),
  ('CUST-AN-016', 'Catering Avia Utama', 'MEDIUM'),
  ('CUST-AN-017', 'Citra Media Advertising', 'LOW'),
  ('CUST-AN-018', 'Telko Solusindo', 'HIGH'),
  ('CUST-AN-019', 'Angkasa Retail Group', 'HIGH'),
  ('CUST-AN-020', 'Solusi Parkir Bandara', 'LOW');

-- ─── Contracts (Compiled_Contracts + Min_GPM_Target from Revenue_Data) ─────

insert into public.contracts (
  id, customer_id, business_line, service_type, contract_end_date, source_end_date,
  tarif, cost, min_gpm_target
) values
  ('efb4a100-e67a-4258-bb92-082aa7745462', 'CUST-GH-001', 'Ground Handling', 'Narrow Body B737',
   current_date + (date '2026-09-15' - date '2026-08-10'), date '2026-09-15', 12500000, 9000000, 0.25),
  ('387db85c-523a-4340-994f-ff91fb734514', 'CUST-GH-002', 'Ground Handling', 'Wide Body B777',
   current_date + (date '2026-08-30' - date '2026-08-10'), date '2026-08-30', 31000000, 24000000, 0.2),
  ('a50722d9-9c3b-461b-a586-26a566a54eed', 'CUST-GH-003', 'Ground Handling', 'Private Jet Handling',
   current_date + (date '2026-10-12' - date '2026-08-10'), date '2026-10-12', 18000000, 13000000, 0.25),
  ('3cfd6600-8bb1-4582-8f95-db99d5a5c48b', 'CUST-GH-004', 'Ground Handling', 'Narrow Body A320',
   current_date + (date '2026-07-25' - date '2026-08-10'), date '2026-07-25', 11800000, 8800000, 0.25),
  ('593f5bbf-acc1-440c-9574-a9b601f216ef', 'CUST-GH-005', 'Ground Handling', 'Narrow Body B737',
   current_date + (date '2026-11-05' - date '2026-08-10'), date '2026-11-05', 12200000, 9150000, 0.22),
  ('39fc3439-43be-4070-ae60-2430ebf4daca', 'CUST-GH-006', 'Ground Handling', 'Freighter B737-F',
   current_date + (date '2026-08-15' - date '2026-08-10'), date '2026-08-15', 22000000, 17500000, 0.2),
  ('702982ab-ee6b-4b32-91a4-651c2c7a8c80', 'CUST-GH-007', 'Ground Handling', 'Turboprop ATR72',
   current_date + (date '2026-12-01' - date '2026-08-10'), date '2026-12-01', 7500000, 5500000, 0.25),
  ('e7c1a3b7-89d7-4f69-8445-67413e12bd98', 'CUST-GH-008', 'Ground Handling', 'Narrow Body A320',
   current_date + (date '2026-09-20' - date '2026-08-10'), date '2026-09-20', 11900000, 8900000, 0.24),
  ('d140de91-fe81-481e-a92f-7f00e130387a', 'CUST-CG-009', 'Cargo & Warehouse', 'GENCO',
   current_date + (date '2026-08-01' - date '2026-08-10'), date '2026-08-01', 4500, 3200, 0.25),
  ('84d6be44-13fd-4eaf-9e6a-ba5cebdc8511', 'CUST-CG-010', 'Cargo & Warehouse', 'GENCO',
   current_date + (date '2026-10-18' - date '2026-08-10'), date '2026-10-18', 8500, 6100, 0.25),
  ('a1e6138d-344e-41e1-99b4-6b48eb3f0b48', 'CUST-CG-011', 'Cargo & Warehouse', 'GENCO',
   current_date + (date '2026-07-30' - date '2026-08-10'), date '2026-07-30', 11000, 7800, 0.3),
  ('c99ab930-bd34-44a5-945b-1762427dfba7', 'CUST-CG-012', 'Cargo & Warehouse', 'GENCO',
   current_date + (date '2026-08-10' - date '2026-08-10'), date '2026-08-10', 9000, 6900, 0.2),
  ('e6118caa-61e1-4779-ae47-2e25c78d1dfd', 'CUST-CG-013', 'Cargo & Warehouse', 'DG',
   current_date + (date '2026-11-15' - date '2026-08-10'), date '2026-11-15', 4200, 3100, 0.22),
  ('b4378a8e-0fe9-4e36-9497-68b81b858628', 'CUST-CG-014', 'Cargo & Warehouse', 'DG',
   current_date + (date '2026-12-10' - date '2026-08-10'), date '2026-12-10', 8200, 6000, 0.25),
  ('52ec02ab-1996-46e2-8927-62b0572340e9', 'CUST-CG-015', 'Cargo & Warehouse', 'DG',
   current_date + (date '2026-09-05' - date '2026-08-10'), date '2026-09-05', 11500, 8200, 0.28),
  ('3c6819e4-eabf-4833-93cc-1ab13ebec5ed', 'CUST-AN-016', 'Ancillary Business', 'Concierge',
   current_date + (date '2026-10-10' - date '2026-08-10'), date '2026-10-10', 250000, 160000, 0.35),
  ('7cc61bc3-7fa9-433c-b57e-c067c9eba6ad', 'CUST-AN-017', 'Ancillary Business', 'Learning Centre',
   current_date + (date '2026-12-05' - date '2026-08-10'), date '2026-12-05', 45000000, 28000000, 0.3),
  ('aac8a6b3-7d71-4e69-ba10-3fd26c3b2e9b', 'CUST-AN-018', 'Ancillary Business', 'Concierge',
   current_date + (date '2026-10-05' - date '2026-08-10'), date '2026-10-05', 75000000, 48000000, 0.35),
  ('30a91423-8baa-4910-8b84-0daa28ab1f04', 'CUST-AN-019', 'Ancillary Business', 'Concierge',
   current_date + (date '2026-11-30' - date '2026-08-10'), date '2026-11-30', 120000000, 85000000, 0.25),
  ('7b4a4df7-e55b-44d4-bb6d-1135e66abe4d', 'CUST-AN-020', 'Ancillary Business', 'Learning Centre',
   current_date + (date '2026-08-22' - date '2026-08-10'), date '2026-08-22', 35000000, 22000000, 0.35);

-- ─── Service cases (CS_Data) ──────────────────────────────────────────────
-- Read-only reference data: no role owns case entry.

insert into public.cases (customer_id, description, status) values
  ('CUST-GH-001', 'Kerusakan peralatan GSE saat pushback pesawat wide-body.', 'OPEN'),
  ('CUST-GH-001', 'Keterlambatan penanganan bagasi (delay 45 menit) GA-120.', 'CLOSED'),
  ('CUST-GH-002', 'Tumpahan oli hidrolik pesawat di apron saat bongkar muat bagasi.', 'OPEN'),
  ('CUST-GH-006', 'Keterlambatan bongkar muat kargo kargo utama (delay 60 menit).', 'CLOSED'),
  ('CUST-CG-011', 'Komplain suhu ruang pendingin naik melebihi batas toleransi.', 'OPEN'),
  ('CUST-CG-012', 'Kerusakan fisik pada kotak pengiriman buah segar kustomer.', 'OPEN'),
  ('CUST-CG-014', 'Kehilangan satu koli dokumen ekspres (sudah ditemukan kembali).', 'CLOSED'),
  ('CUST-AN-016', 'Fasilitas AC di executive lounge bandara sempat mati selama 2 jam.', 'CLOSED'),
  ('CUST-AN-019', 'Kebocoran atap gerai ritel di area terminal internasional.', 'OPEN'),
  ('CUST-AN-020', 'Antrean panjang valet parking saat jam sibuk penerbangan pagi.', 'OPEN');

commit;
