-- Generated by scripts/generate-seed.ts from Master_Database_Komersial_Compiled.xlsx.
-- Do not edit by hand; run `pnpm seed:generate` instead.
--
-- Contract end dates are re-anchored on every reset: current_date + (source_end_date - '2026-08-10'),
-- which reproduces the pipeline of Nonaktif 3 / Kritis 3 / Perlu Perhatian 5 / Aman 9.

begin;

-- ─── Demo accounts ────────────────────────────────────────────────────────
-- One Commercial user per business line plus one VP: four logins, four distinct
-- row sets. The largest Commercial scope still hides 60% of the portfolio.

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  -- GoTrue scans these into non-nullable Go strings; leaving them NULL makes
  -- every sign-in fail with "Database error querying schema".
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) values (
  '00000000-0000-0000-0000-000000000000', '4d4e32fa-98f2-4b0a-9b60-c3b71488ec80', 'authenticated', 'authenticated',
  'vp@gapura.test', crypt('Gapura2026!', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{"nama":"Rizal Pratama"}',
  now(), now(), '', '', '', '', '', '', '', ''
);

insert into auth.identities (
  id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at
) values (
  gen_random_uuid(), '4d4e32fa-98f2-4b0a-9b60-c3b71488ec80', '4d4e32fa-98f2-4b0a-9b60-c3b71488ec80', 'email',
  '{"sub":"4d4e32fa-98f2-4b0a-9b60-c3b71488ec80","email":"vp@gapura.test","email_verified":true}',
  now(), now(), now()
);

insert into public.profiles (id, nama, role, business_line) values (
  '4d4e32fa-98f2-4b0a-9b60-c3b71488ec80', 'Rizal Pratama', 'vp',
  null
);

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  -- GoTrue scans these into non-nullable Go strings; leaving them NULL makes
  -- every sign-in fail with "Database error querying schema".
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) values (
  '00000000-0000-0000-0000-000000000000', 'a82b8f9b-cad3-4f3e-a615-1b4865af5bbc', 'authenticated', 'authenticated',
  'ground.handling@gapura.test', crypt('Gapura2026!', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{"nama":"Arief Budiman"}',
  now(), now(), '', '', '', '', '', '', '', ''
);

insert into auth.identities (
  id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at
) values (
  gen_random_uuid(), 'a82b8f9b-cad3-4f3e-a615-1b4865af5bbc', 'a82b8f9b-cad3-4f3e-a615-1b4865af5bbc', 'email',
  '{"sub":"a82b8f9b-cad3-4f3e-a615-1b4865af5bbc","email":"ground.handling@gapura.test","email_verified":true}',
  now(), now(), now()
);

insert into public.profiles (id, nama, role, business_line) values (
  'a82b8f9b-cad3-4f3e-a615-1b4865af5bbc', 'Arief Budiman', 'commercial',
  'Ground Handling'
);

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  -- GoTrue scans these into non-nullable Go strings; leaving them NULL makes
  -- every sign-in fail with "Database error querying schema".
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) values (
  '00000000-0000-0000-0000-000000000000', 'e07f4493-b4c0-4aee-a011-8324388bcd60', 'authenticated', 'authenticated',
  'cargo@gapura.test', crypt('Gapura2026!', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{"nama":"Sari Dewi"}',
  now(), now(), '', '', '', '', '', '', '', ''
);

insert into auth.identities (
  id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at
) values (
  gen_random_uuid(), 'e07f4493-b4c0-4aee-a011-8324388bcd60', 'e07f4493-b4c0-4aee-a011-8324388bcd60', 'email',
  '{"sub":"e07f4493-b4c0-4aee-a011-8324388bcd60","email":"cargo@gapura.test","email_verified":true}',
  now(), now(), now()
);

insert into public.profiles (id, nama, role, business_line) values (
  'e07f4493-b4c0-4aee-a011-8324388bcd60', 'Sari Dewi', 'commercial',
  'Cargo & Warehouse'
);

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  -- GoTrue scans these into non-nullable Go strings; leaving them NULL makes
  -- every sign-in fail with "Database error querying schema".
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token, reauthentication_token
) values (
  '00000000-0000-0000-0000-000000000000', 'efc100a7-0ec5-4e7c-8b00-58a630a52592', 'authenticated', 'authenticated',
  'ancillary@gapura.test', crypt('Gapura2026!', gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{"nama":"Hendra Wijaya"}',
  now(), now(), '', '', '', '', '', '', '', ''
);

insert into auth.identities (
  id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at
) values (
  gen_random_uuid(), 'efc100a7-0ec5-4e7c-8b00-58a630a52592', 'efc100a7-0ec5-4e7c-8b00-58a630a52592', 'email',
  '{"sub":"efc100a7-0ec5-4e7c-8b00-58a630a52592","email":"ancillary@gapura.test","email_verified":true}',
  now(), now(), now()
);

insert into public.profiles (id, nama, role, business_line) values (
  'efc100a7-0ec5-4e7c-8b00-58a630a52592', 'Hendra Wijaya', 'commercial',
  'Ancillary Business'
);

-- ─── Customers (CRM_Data) ─────────────────────────────────────────────────

insert into public.customers (customer_id, nama, rfm_status) values
  ('CUST-GH-001', 'Garuda Nusantara Airlines', 'HIGH'),
  ('CUST-GH-002', 'Lion Star Airways', 'HIGH'),
  ('CUST-GH-003', 'Batavia Air Charter', 'MEDIUM'),
  ('CUST-GH-004', 'Celebes Inter Air', 'MEDIUM'),
  ('CUST-GH-005', 'Sumatra Express Airways', 'LOW'),
  ('CUST-GH-006', 'Borneo Cargo Wings', 'HIGH'),
  ('CUST-GH-007', 'Air Papua Charter', 'LOW'),
  ('CUST-GH-008', 'Bali Sunshine Airways', 'MEDIUM'),
  ('CUST-CG-009', 'Logistik Maju Bersama', 'HIGH'),
  ('CUST-CG-010', 'Jasa Kilat Express', 'MEDIUM'),
  ('CUST-CG-011', 'Samudera Cold Chain', 'HIGH'),
  ('CUST-CG-012', 'Agro Trans Nusantara', 'LOW'),
  ('CUST-CG-013', 'Indo Logistic Solusi', 'LOW'),
  ('CUST-CG-014', 'Global Express Courier', 'HIGH'),
  ('CUST-CG-015', 'Fast Cargo Indonesia', 'MEDIUM'),
  ('CUST-AN-016', 'Catering Avia Utama', 'MEDIUM'),
  ('CUST-AN-017', 'Citra Media Advertising', 'LOW'),
  ('CUST-AN-018', 'Telko Solusindo', 'HIGH'),
  ('CUST-AN-019', 'Angkasa Retail Group', 'HIGH'),
  ('CUST-AN-020', 'Solusi Parkir Bandara', 'LOW');

-- ─── Contracts (Compiled_Contracts + Min_GPM_Target from Revenue_Data) ─────

insert into public.contracts (
  id, customer_id, business_line, service_type, contract_end_date, source_end_date,
  tarif, cost, min_gpm_target
) values
  ('6e80490f-1a60-447f-8677-582c506e04d8', 'CUST-GH-001', 'Ground Handling', 'Narrow Body B737',
   current_date + (date '2026-09-15' - date '2026-08-10'), date '2026-09-15', 12500000, 9000000, 0.25),
  ('609f1c19-b057-4b49-badb-570a7abf598b', 'CUST-GH-002', 'Ground Handling', 'Wide Body B777',
   current_date + (date '2026-08-30' - date '2026-08-10'), date '2026-08-30', 31000000, 24000000, 0.2),
  ('91c39617-7226-491c-9619-8ab9c7c1d4a9', 'CUST-GH-003', 'Ground Handling', 'Private Jet Handling',
   current_date + (date '2026-10-12' - date '2026-08-10'), date '2026-10-12', 18000000, 13000000, 0.25),
  ('91eac21f-12c7-4296-8db8-82715694a6db', 'CUST-GH-004', 'Ground Handling', 'Narrow Body A320',
   current_date + (date '2026-07-25' - date '2026-08-10'), date '2026-07-25', 11800000, 8800000, 0.25),
  ('c387a1f0-6683-4575-98ce-67951109cc1f', 'CUST-GH-005', 'Ground Handling', 'Narrow Body B737',
   current_date + (date '2026-11-05' - date '2026-08-10'), date '2026-11-05', 12200000, 9150000, 0.22),
  ('bfa28df4-d0dc-466e-96b6-1944f14acc67', 'CUST-GH-006', 'Ground Handling', 'Freighter B737-F',
   current_date + (date '2026-08-15' - date '2026-08-10'), date '2026-08-15', 22000000, 17500000, 0.2),
  ('7a13ecda-0370-4770-aa14-b7fb912c7abe', 'CUST-GH-007', 'Ground Handling', 'Turboprop ATR72',
   current_date + (date '2026-12-01' - date '2026-08-10'), date '2026-12-01', 7500000, 5500000, 0.25),
  ('2447c0c7-6cca-4c98-87bc-0745318bbe6b', 'CUST-GH-008', 'Ground Handling', 'Narrow Body A320',
   current_date + (date '2026-09-20' - date '2026-08-10'), date '2026-09-20', 11900000, 8900000, 0.24),
  ('58190558-e636-4603-8328-1c91edab97bc', 'CUST-CG-009', 'Cargo & Warehouse', 'GENCO',
   current_date + (date '2026-08-01' - date '2026-08-10'), date '2026-08-01', 4500, 3200, 0.25),
  ('7f0e5ea1-2dfe-4e19-8e06-c48126e4e8cf', 'CUST-CG-010', 'Cargo & Warehouse', 'GENCO',
   current_date + (date '2026-10-18' - date '2026-08-10'), date '2026-10-18', 8500, 6100, 0.25),
  ('27ae0bb7-6ea7-4b4d-b851-d0dd8ba20851', 'CUST-CG-011', 'Cargo & Warehouse', 'GENCO',
   current_date + (date '2026-07-30' - date '2026-08-10'), date '2026-07-30', 11000, 7800, 0.3),
  ('6b9df9a4-ed77-484e-bfb4-c13da4b507d6', 'CUST-CG-012', 'Cargo & Warehouse', 'GENCO',
   current_date + (date '2026-08-10' - date '2026-08-10'), date '2026-08-10', 9000, 6900, 0.2),
  ('8098be4f-953c-4c3f-9048-3204d5d13785', 'CUST-CG-013', 'Cargo & Warehouse', 'DG',
   current_date + (date '2026-11-15' - date '2026-08-10'), date '2026-11-15', 4200, 3100, 0.22),
  ('44a3ac1e-6e7e-461c-a5af-9f11952ffa93', 'CUST-CG-014', 'Cargo & Warehouse', 'DG',
   current_date + (date '2026-12-10' - date '2026-08-10'), date '2026-12-10', 8200, 6000, 0.25),
  ('2f915fdf-fd1c-478b-a756-66b74da6fa32', 'CUST-CG-015', 'Cargo & Warehouse', 'DG',
   current_date + (date '2026-09-05' - date '2026-08-10'), date '2026-09-05', 11500, 8200, 0.28),
  ('f0ca37a7-6993-4f9c-bfaf-a36654b15335', 'CUST-AN-016', 'Ancillary Business', 'Concierge',
   current_date + (date '2026-10-10' - date '2026-08-10'), date '2026-10-10', 250000, 160000, 0.35),
  ('08e24c1e-18c3-4fda-a021-433b8b21e7d1', 'CUST-AN-017', 'Ancillary Business', 'Learning Centre',
   current_date + (date '2026-12-05' - date '2026-08-10'), date '2026-12-05', 45000000, 28000000, 0.3),
  ('ba77a4c8-49ae-4b53-97f0-6664c29691ae', 'CUST-AN-018', 'Ancillary Business', 'Concierge',
   current_date + (date '2026-10-05' - date '2026-08-10'), date '2026-10-05', 75000000, 48000000, 0.35),
  ('d74ad584-2464-4add-b142-d69cdfae01bf', 'CUST-AN-019', 'Ancillary Business', 'Concierge',
   current_date + (date '2026-11-30' - date '2026-08-10'), date '2026-11-30', 120000000, 85000000, 0.25),
  ('19d99ad3-6b34-4e7f-a2f3-1f241014a447', 'CUST-AN-020', 'Ancillary Business', 'Learning Centre',
   current_date + (date '2026-08-22' - date '2026-08-10'), date '2026-08-22', 35000000, 22000000, 0.35);

-- ─── Service cases (CS_Data) ──────────────────────────────────────────────
-- Read-only reference data: no role owns case entry.

insert into public.cases (customer_id, description, status) values
  ('CUST-GH-001', 'Kerusakan peralatan GSE saat pushback pesawat wide-body.', 'OPEN'),
  ('CUST-GH-001', 'Keterlambatan penanganan bagasi (delay 45 menit) GA-120.', 'CLOSED'),
  ('CUST-GH-002', 'Tumpahan oli hidrolik pesawat di apron saat bongkar muat bagasi.', 'OPEN'),
  ('CUST-GH-006', 'Keterlambatan bongkar muat kargo kargo utama (delay 60 menit).', 'CLOSED'),
  ('CUST-CG-011', 'Komplain suhu ruang pendingin naik melebihi batas toleransi.', 'OPEN'),
  ('CUST-CG-012', 'Kerusakan fisik pada kotak pengiriman buah segar kustomer.', 'OPEN'),
  ('CUST-CG-014', 'Kehilangan satu koli dokumen ekspres (sudah ditemukan kembali).', 'CLOSED'),
  ('CUST-AN-016', 'Fasilitas AC di executive lounge bandara sempat mati selama 2 jam.', 'CLOSED'),
  ('CUST-AN-019', 'Kebocoran atap gerai ritel di area terminal internasional.', 'OPEN'),
  ('CUST-AN-020', 'Antrean panjang valet parking saat jam sibuk penerbangan pagi.', 'OPEN');

commit;
