/**
 * Generates supabase/seed.sql from the Google Sheet.
 *
 * Run with `pnpm seed:generate` after the Sheet changes. The output is committed so
 * that `supabase db reset` needs neither Google credentials nor this script, and so
 * that what was seeded is reviewable in a diff rather than only observable in a
 * database.
 *
 * The Sheet replaced the workbook as the source of truth. `scripts/lib/read-workbook.ts`
 * is left in place for the record but nothing calls it.
 *
 * The seed **replaces** rather than appends: it deletes the rows it owns before
 * inserting. That is what makes `pnpm deploy:db --seed` safe to run twice, and it is
 * also what makes it destructive — deleting a contract cascades to its scenarios and
 * notifications.
 */
import { randomUUID } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { config } from 'dotenv'

import { DEMO_ACCOUNTS } from '../src/lib/demo-accounts.ts'
import { readSheet } from './lib/read-sheet.ts'

config({ path: '.env.local', quiet: true })

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..')

const quote = (value: string): string => `'${value.replace(/'/g, "''")}'`
const nullable = (value: string | null): string => (value === null ? 'null' : quote(value))
const nullableNumber = (value: number | null): string => (value === null ? 'null' : String(value))

const sheet = await readSheet()

// Fail loudly rather than seed a database that misrepresents the source.
if (sheet.customers.length === 0) throw new Error('CRM_Data produced no customers')
if (sheet.contracts.length === 0) throw new Error('Compiled_Contracts produced no contracts')

const accountIds = new Map(DEMO_ACCOUNTS.map((a) => [a.email, randomUUID()]))

const lines: string[] = []
const emit = (...parts: string[]): void => {
  lines.push(...parts)
}

emit(
  '-- Generated by scripts/generate-seed.ts from the Google Sheet',
  '-- "Master_Database_Komersial_Compiled". Do not edit by hand; run `pnpm seed:generate`.',
  '--',
  "-- Dates are the Sheet's own and are maintained there. They are no longer re-anchored",
  '-- on seeding: the workbook needed that because its dates aged, the Sheet does not.',
  '--',
  '-- A contract with a null `cabang` is the Sheet\'s "All Station" — work belonging to',
  '-- every airport, and therefore visible at every branch rather than at none.',
  '',
  'begin;',
  '',
  '-- ─── Replace what the Sheet owns ──────────────────────────────────────────',
  '-- Deleting a contract cascades to its scenarios and notifications, which is what',
  '-- makes re-seeding a clean replacement rather than a merge.',
  '',
  'delete from public.cases;',
  'delete from public.contracts;',
  'delete from public.customers;',
  `delete from auth.users where email in (${DEMO_ACCOUNTS.map((a) => quote(a.email)).join(', ')});`,
  '',
  '-- ─── Demo accounts ────────────────────────────────────────────────────────',
  '-- One login per role. VP and Commercial are unscoped; the GM Cabang is confined to',
  '-- one station and is the boundary a judge can sign in and see.',
  '',
)

for (const account of DEMO_ACCOUNTS) {
  const id = accountIds.get(account.email)!
  emit(
    'insert into auth.users (',
    '  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,',
    '  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,',
    '  -- GoTrue scans these into non-nullable Go strings; leaving them NULL makes',
    '  -- every sign-in fail with "Database error querying schema".',
    '  confirmation_token, recovery_token, email_change_token_new, email_change,',
    '  email_change_token_current, phone_change, phone_change_token, reauthentication_token',
    ') values (',
    `  '00000000-0000-0000-0000-000000000000', '${id}', 'authenticated', 'authenticated',`,
    `  ${quote(account.email)}, crypt(${quote(account.password)}, gen_salt('bf')), now(),`,
    `  '{"provider":"email","providers":["email"]}', ${quote(JSON.stringify({ nama: account.nama }))},`,
    "  now(), now(), '', '', '', '', '', '', '', ''",
    ');',
    '',
    'insert into auth.identities (',
    '  id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at',
    ') values (',
    `  gen_random_uuid(), '${id}', '${id}', 'email',`,
    `  ${quote(JSON.stringify({ sub: id, email: account.email, email_verified: true }))},`,
    '  now(), now(), now()',
    ');',
    '',
    'insert into public.profiles (id, nama, role, business_line, cabang) values (',
    `  '${id}', ${quote(account.nama)}, ${quote(account.role)},`,
    `  ${account.businessLine === null ? 'null' : quote(account.businessLine)},`,
    `  ${account.cabang === null ? 'null' : quote(account.cabang)}`,
    ');',
    '',
  )
}

emit(
  '-- ─── Customers (CRM_Data) ─────────────────────────────────────────────────',
  '',
  'insert into public.customers (customer_id, nama, rfm_status, frequency_score, monetary_score, recency_score) values',
)
emit(
  sheet.customers
    .map(
      (c, i) =>
        `  (${quote(c.customerId)}, ${quote(c.nama)}, ${quote(c.rfmStatus)}, ` +
        `${nullableNumber(c.frequencyScore)}, ${nullableNumber(c.monetaryScore)}, ${nullableNumber(c.recencyScore)})` +
        (i === sheet.customers.length - 1 ? ';' : ','),
    )
    .join('\n'),
  '',
)

emit(
  '-- ─── Contracts (Compiled_Contracts), one row per station ──────────────────',
  '-- The Sheet writes multi-station work either as one row listing several stations or',
  '-- as several rows priced individually; both arrive here as one row per station.',
  '--',
  '-- `min_gpm_target` and `service_type` are null throughout: the Sheet has no column',
  '-- for either, and Revenue_Data still keys on the retired CUST-GH-* ids so it cannot',
  '-- supply the target. Nulls rather than invented figures.',
  '',
  'insert into public.contracts (',
  '  id, contract_no, customer_id, cabang, business_line, contract_start_date, contract_end_date,',
  '  tarif, cost, pic_nama, pic_telepon, pic_email, remarks, latest_contract',
  ') values',
)
emit(
  sheet.contracts
    .map(
      (c, i) =>
        `  ('${randomUUID()}', ${quote(c.contractNo)}, ${quote(c.customerId)}, ${nullable(c.cabang)}, ${quote(c.businessLine)},\n` +
        `   ${nullable(c.contractStartDate)}, ${quote(c.contractEndDate)}, ${c.tarif}, ${c.cost},\n` +
        `   ${nullable(c.picNama)}, ${nullable(c.picTelepon)}, ${nullable(c.picEmail)}, ${nullable(c.remarks)}, ${nullable(c.latestContract)})` +
        (i === sheet.contracts.length - 1 ? ';' : ','),
    )
    .join('\n'),
  '',
)

emit('-- ─── Service cases (CS_Data) ──────────────────────────────────────────────', '')
// `insert … values` with no rows is a syntax error, so an empty CS_Data has to emit
// no statement rather than a truncated one.
if (sheet.cases.length === 0) {
  emit('-- CS_Data is empty; no cases to seed.', '')
} else {
  emit('insert into public.cases (customer_id, description, status) values')
  emit(
    sheet.cases
      .map(
        (c, i) =>
          `  (${quote(c.customerId)}, ${quote(c.description)}, ${quote(c.status)})` +
          (i === sheet.cases.length - 1 ? ';' : ','),
      )
      .join('\n'),
    '',
  )
}
emit('commit;', '')

const outputPath = join(repoRoot, 'supabase', 'seed.sql')
writeFileSync(outputPath, lines.join('\n'))

const tally = <T>(rows: T[], key: (row: T) => string): string => {
  const counts = new Map<string, number>()
  for (const row of rows) counts.set(key(row), (counts.get(key(row)) ?? 0) + 1)
  return [...counts]
    .sort()
    .map(([k, n]) => `${k} ${n}`)
    .join(', ')
}

console.log(`Wrote ${outputPath}`)
console.log(
  `  ${sheet.customers.length} customers, ${sheet.contracts.length} contract lines, ${sheet.cases.length} cases`,
)
console.log(`  business line: ${tally(sheet.contracts, (c) => c.businessLine)}`)
console.log(`  cabang: ${tally(sheet.contracts, (c) => c.cabang ?? 'All Station')}`)
