/**
 * Generates supabase/seed.sql from the source workbook.
 *
 * Run with `pnpm seed:generate` after the workbook changes. The output is committed
 * so that `supabase db reset` needs neither the workbook nor this script.
 */
import { randomUUID } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { DEMO_ACCOUNTS } from '../src/lib/demo-accounts.ts'
import { readWorkbook } from './lib/read-workbook.ts'

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..')

/**
 * The date on which the workbook's own end dates produce the spec's stated pipeline:
 * Nonaktif 3, Kritis 3, Perlu Perhatian 5, Aman 9.
 *
 * Seeding stores each contract's end date as `current_date + (source - anchor)`, so
 * every `db reset` reproduces that same distribution however long after the workbook
 * was written the demo is given. The workbook's absolute date is kept in
 * `source_end_date` so nothing is lost.
 */
const PIPELINE_ANCHOR = '2026-08-10'

const quote = (value: string): string => `'${value.replace(/'/g, "''")}'`

const workbook = readWorkbook(join(repoRoot, 'Master_Database_Komersial_Compiled.xlsx'))

// Fail loudly rather than seed a database that misrepresents the source.
if (workbook.contracts.length !== 20) {
  throw new Error(`expected 20 contracts in the workbook, found ${workbook.contracts.length}`)
}
if (workbook.cases.length !== 10) {
  throw new Error(`expected 10 cases in the workbook, found ${workbook.cases.length}`)
}

const contractIds = new Map(workbook.contracts.map((c) => [c.customerId, randomUUID()]))
const accountIds = new Map(DEMO_ACCOUNTS.map((a) => [a.email, randomUUID()]))

const lines: string[] = []
const emit = (...parts: string[]): void => {
  lines.push(...parts)
}

emit(
  '-- Generated by scripts/generate-seed.ts from Master_Database_Komersial_Compiled.xlsx.',
  '-- Do not edit by hand; run `pnpm seed:generate` instead.',
  '--',
  `-- Contract end dates are re-anchored on every reset: current_date + (source_end_date - '${PIPELINE_ANCHOR}'),`,
  '-- which reproduces the pipeline of Nonaktif 3 / Kritis 3 / Perlu Perhatian 5 / Aman 9.',
  '',
  'begin;',
  '',
  '-- ─── Demo accounts ────────────────────────────────────────────────────────',
  '-- One Commercial user per business line plus one VP: four logins, four distinct',
  '-- row sets. The largest Commercial scope still hides 60% of the portfolio.',
  '',
)

for (const account of DEMO_ACCOUNTS) {
  const id = accountIds.get(account.email)!
  emit(
    'insert into auth.users (',
    '  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,',
    '  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,',
    '  -- GoTrue scans these into non-nullable Go strings; leaving them NULL makes',
    '  -- every sign-in fail with "Database error querying schema".',
    '  confirmation_token, recovery_token, email_change_token_new, email_change,',
    '  email_change_token_current, phone_change, phone_change_token, reauthentication_token',
    ') values (',
    `  '00000000-0000-0000-0000-000000000000', '${id}', 'authenticated', 'authenticated',`,
    `  ${quote(account.email)}, crypt(${quote(account.password)}, gen_salt('bf')), now(),`,
    `  '{"provider":"email","providers":["email"]}', ${quote(JSON.stringify({ nama: account.nama }))},`,
    "  now(), now(), '', '', '', '', '', '', '', ''",
    ');',
    '',
    'insert into auth.identities (',
    '  id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at',
    ') values (',
    `  gen_random_uuid(), '${id}', '${id}', 'email',`,
    `  ${quote(JSON.stringify({ sub: id, email: account.email, email_verified: true }))},`,
    '  now(), now(), now()',
    ');',
    '',
    'insert into public.profiles (id, nama, role, business_line) values (',
    `  '${id}', ${quote(account.nama)}, ${quote(account.role)},`,
    `  ${account.businessLine === null ? 'null' : quote(account.businessLine)}`,
    ');',
    '',
  )
}

emit(
  '-- ─── Customers (CRM_Data) ─────────────────────────────────────────────────',
  '',
  'insert into public.customers (customer_id, nama, rfm_status) values',
)
emit(
  workbook.contracts
    .map(
      (c, i) =>
        `  (${quote(c.customerId)}, ${quote(c.customerName)}, ${quote(c.rfmStatus)})` +
        (i === workbook.contracts.length - 1 ? ';' : ','),
    )
    .join('\n'),
  '',
)

emit(
  '-- ─── Contracts (Compiled_Contracts + Min_GPM_Target from Revenue_Data) ─────',
  '',
  'insert into public.contracts (',
  '  id, customer_id, business_line, service_type, contract_end_date, source_end_date,',
  '  tarif, cost, min_gpm_target',
  ') values',
)
emit(
  workbook.contracts
    .map((c, i) => {
      const id = contractIds.get(c.customerId)!
      const endDate = `current_date + (date '${c.sourceEndDate}' - date '${PIPELINE_ANCHOR}')`
      return (
        `  ('${id}', ${quote(c.customerId)}, ${quote(c.businessLine)}, ${quote(c.serviceType)},\n` +
        `   ${endDate}, date '${c.sourceEndDate}', ${c.tarif}, ${c.cost}, ${c.minGpmTarget})` +
        (i === workbook.contracts.length - 1 ? ';' : ',')
      )
    })
    .join('\n'),
  '',
)

emit(
  '-- ─── Service cases (CS_Data) ──────────────────────────────────────────────',
  '-- Read-only reference data: no role owns case entry.',
  '',
  'insert into public.cases (customer_id, description, status) values',
)
emit(
  workbook.cases
    .map(
      (c, i) =>
        `  (${quote(c.customerId)}, ${quote(c.description)}, ${quote(c.status)})` +
        (i === workbook.cases.length - 1 ? ';' : ','),
    )
    .join('\n'),
  '',
  'commit;',
  '',
)

const outputPath = join(repoRoot, 'supabase', 'seed.sql')
writeFileSync(outputPath, lines.join('\n'))

const byLine = new Map<string, number>()
for (const c of workbook.contracts) byLine.set(c.businessLine, (byLine.get(c.businessLine) ?? 0) + 1)

console.log(`Wrote ${outputPath}`)
console.log(`  ${workbook.contracts.length} contracts, ${workbook.cases.length} cases`)
for (const [line, count] of byLine) console.log(`  ${line}: ${count}`)
